In [1]:
print("Hello")

Hello


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.0+cpu


In [6]:
## Introduction to tensors
# Creating tensors

In [7]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim


1

In [10]:
vector.shape

torch.Size([2])

In [12]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim


2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [20]:
### Random tensors

In [23]:
# Create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5023, 0.0909, 0.7060, 0.4950],
        [0.3566, 0.7170, 0.8933, 0.2860],
        [0.6664, 0.0558, 0.0672, 0.2141]])

In [24]:
# random image size tensors
random_img_size_tensor = torch.rand(size=(224,224,3)) # height width color_channels
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [25]:
# random image size tensors
random_img_size_tensor

tensor([[[0.1238, 0.9763, 0.8614],
         [0.2650, 0.5583, 0.8248],
         [0.0140, 0.2641, 0.7104],
         ...,
         [0.3174, 0.7416, 0.3782],
         [0.3729, 0.1791, 0.4847],
         [0.5756, 0.4385, 0.6620]],

        [[0.6220, 0.4107, 0.5039],
         [0.7832, 0.5671, 0.6404],
         [0.0404, 0.6167, 0.1231],
         ...,
         [0.3160, 0.2379, 0.5132],
         [0.4547, 0.4654, 0.7840],
         [0.0510, 0.3814, 0.3712]],

        [[0.7115, 0.4858, 0.4931],
         [0.1124, 0.3553, 0.0475],
         [0.8335, 0.2581, 0.5947],
         ...,
         [0.5749, 0.9217, 0.4828],
         [0.3209, 0.4613, 0.1427],
         [0.0926, 0.7232, 0.7491]],

        ...,

        [[0.7540, 0.6054, 0.7299],
         [0.6675, 0.8628, 0.2552],
         [0.3775, 0.8094, 0.3157],
         ...,
         [0.5825, 0.8932, 0.5143],
         [0.3581, 0.8467, 0.8923],
         [0.1228, 0.7885, 0.1519]],

        [[0.5223, 0.5880, 0.5914],
         [0.8240, 0.0399, 0.8267],
         [0.

In [27]:
# create tensors of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# create tensors of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype


torch.float32

In [30]:
# torch.range()
torch.range(0,10)

C:\Users\hp\AppData\Local\Temp\ipykernel_4552\1265344515.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
torch.arange(0,1000,77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [34]:
# for same shape - tensor-like
one_to_ten = torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])