In [1]:
print("Hello")

Hello


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.0+cpu


In [3]:
## Introduction to tensors
# Creating tensors

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim


1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim


2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [15]:
### Random tensors

In [16]:
# Create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5686, 0.3137, 0.9694, 0.4988],
        [0.4192, 0.8981, 0.1091, 0.7285],
        [0.3785, 0.2914, 0.3298, 0.9968]])

In [17]:
# random image size tensors
random_img_size_tensor = torch.rand(size=(224,224,3)) # height width color_channels
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
# random image size tensors
random_img_size_tensor

tensor([[[0.7259, 0.5428, 0.4092],
         [0.6216, 0.1662, 0.2609],
         [0.0080, 0.4469, 0.0758],
         ...,
         [0.9292, 0.5836, 0.5416],
         [0.1612, 0.8458, 0.8983],
         [0.0613, 0.8989, 0.0983]],

        [[0.4310, 0.8107, 0.2160],
         [0.1925, 0.0668, 0.8988],
         [0.6877, 0.3230, 0.6250],
         ...,
         [0.3374, 0.9607, 0.7135],
         [0.6001, 0.4154, 0.8877],
         [0.4666, 0.2790, 0.8497]],

        [[0.6517, 0.0350, 0.1926],
         [0.0109, 0.8832, 0.6167],
         [0.2875, 0.3147, 0.1774],
         ...,
         [0.7779, 0.6886, 0.4072],
         [0.4727, 0.9365, 0.1512],
         [0.0779, 0.1083, 0.4837]],

        ...,

        [[0.8747, 0.8680, 0.6037],
         [0.4093, 0.2172, 0.5673],
         [0.4641, 0.4042, 0.7442],
         ...,
         [0.9997, 0.1336, 0.4564],
         [0.1659, 0.0829, 0.8693],
         [0.1980, 0.4047, 0.1034]],

        [[0.9223, 0.8364, 0.3618],
         [0.4804, 0.9595, 0.9412],
         [0.

In [19]:
# create tensors of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# create tensors of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype


torch.float32

In [22]:
# torch.range()
torch.range(0,10)

C:\Users\hp\AppData\Local\Temp\ipykernel_12156\1265344515.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
torch.arange(0,1000,77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [24]:
# for same shape - tensor-like
one_to_ten = torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
### Data Types
float32_dataType = torch.tensor([3.0,6.0,9.0],
                                 dtype=None,
                                 device=None,
                                 requires_grad=False)
float32_dataType

tensor([3., 6., 9.])

In [27]:
float32_dataType.dtype

torch.float32

In [29]:
## tensor data types are the 3 major reasons of error in pytorch and deep learning
# 1 tensor not right datatype
# 2 tensor not right shape
# 3 tensors are not on the right device


In [30]:
float16_dataType_tensor = float32_dataType.type(torch.float16)
float16_dataType_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float16_dataType_tensor * float32_dataType

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [34]:
float32_dataType * int_32_tensor

tensor([ 9., 36., 81.])

In [35]:
# Creating a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9858, 0.4201, 0.0733, 0.0725],
        [0.2714, 0.7731, 0.4894, 0.3738],
        [0.8266, 0.4373, 0.0652, 0.8473]])

In [36]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [37]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.9858, 0.4201, 0.0733, 0.0725],
        [0.2714, 0.7731, 0.4894, 0.3738],
        [0.8266, 0.4373, 0.0652, 0.8473]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [38]:
# tensor operation
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [39]:
tensor *10

tensor([10, 20, 30])

In [40]:
tensor - 10


tensor([-9, -8, -7])

In [41]:
tensor/8


tensor([0.1250, 0.2500, 0.3750])

In [42]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [43]:
torch.add(tensor,5)

tensor([6, 7, 8])

In [44]:
# Matrix multiplication

In [45]:
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [46]:
# MAtrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [47]:
%%time
value=0
for i in range(len(tensor)):
    value+=tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 11.8 ms


In [48]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 999 µs


tensor(14)

In [57]:
tensor99 = torch.rand(10000,10000)

In [58]:
%%time
torch.matmul(tensor99,tensor99)

CPU times: total: 49.7 s
Wall time: 28 s


tensor([[2494.4370, 2497.4565, 2511.8162,  ..., 2490.4001, 2484.1040,
         2456.1382],
        [2510.7100, 2537.1270, 2513.8413,  ..., 2506.5837, 2508.9565,
         2471.0774],
        [2466.0032, 2495.4468, 2489.3682,  ..., 2472.5093, 2447.5693,
         2436.2146],
        ...,
        [2482.6587, 2515.2637, 2524.3435,  ..., 2491.4817, 2475.5225,
         2446.9778],
        [2508.4324, 2524.5671, 2514.4092,  ..., 2489.7939, 2478.1348,
         2459.8181],
        [2492.6953, 2501.3279, 2493.8425,  ..., 2470.1758, 2477.8230,
         2436.4678]])

In [60]:
%%time
tensor99@tensor99

CPU times: total: 44.9 s
Wall time: 24.4 s


tensor([[2494.4370, 2497.4565, 2511.8162,  ..., 2490.4001, 2484.1040,
         2456.1382],
        [2510.7100, 2537.1270, 2513.8413,  ..., 2506.5837, 2508.9565,
         2471.0774],
        [2466.0032, 2495.4468, 2489.3682,  ..., 2472.5093, 2447.5693,
         2436.2146],
        ...,
        [2482.6587, 2515.2637, 2524.3435,  ..., 2491.4817, 2475.5225,
         2446.9778],
        [2508.4324, 2524.5671, 2514.4092,  ..., 2489.7939, 2478.1348,
         2459.8181],
        [2492.6953, 2501.3279, 2493.8425,  ..., 2470.1758, 2477.8230,
         2436.4678]])

In [62]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[5,6],
                         [7,8],
                         [9,10]])
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [63]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [64]:
tensor_B.T, tensor_B

(tensor([[ 5,  7,  9],
         [ 6,  8, 10]]),
 tensor([[ 5,  6],
         [ 7,  8],
         [ 9, 10]]))

In [66]:
tensor_B,tensor_B.shape

(tensor([[ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([3, 2]))

In [68]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 5,  7,  9],
         [ 6,  8, 10]]),
 torch.Size([2, 3]))

In [69]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 17,  23,  29],
        [ 39,  53,  67],
        [ 61,  83, 105]])

In [70]:
torch.mm(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

In [71]:
### Finding min max sum etc


In [72]:
#crete a tensor
x = torch.arange(1,100,9)
x, x.dtype

(tensor([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), torch.int64)

In [74]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [75]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [76]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [77]:
torch.mean(x.type(torch.float32))

tensor(46.)

In [78]:
x.type(torch.float32).mean()

tensor(46.)

In [80]:
torch.sum(x), x.sum()

(tensor(506), tensor(506))