In [21]:
!pip show numpy

Name: numpy
Version: 1.26.0
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYR

In [22]:
import numpy as np

In [23]:
%time
# List
a = [1,2,3,4,5]
print(a)
print(a[1])
print(a[1:4])
print(a[-1])
print(type(a))
a[2] = 10
print(a)

CPU times: total: 0 ns
Wall time: 0 ns
[1, 2, 3, 4, 5]
2
[2, 3, 4]
5
<class 'list'>
[1, 2, 10, 4, 5]


In [24]:
%time
# Numpy array
a = np.array([1,2,3,4,5])
print(a)
print(a[1])
print(a[1:4])
print(a[-1])
print(type(a))
a[2] = 10
print(a)

CPU times: total: 0 ns
Wall time: 0 ns
[1 2 3 4 5]
2
[2 3 4]
5
<class 'numpy.ndarray'>
[ 1  2 10  4  5]


In [25]:
%time
a_mul = np.array([[1,2,3,1],
                  [4,5,6,1],
                  [7,8,9,1]])
print(a_mul)
print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)

CPU times: total: 0 ns
Wall time: 0 ns
[[1 2 3 1]
 [4 5 6 1]
 [7 8 9 1]]
(3, 4)
2
12
int32


In [26]:
%time
a_mul = np.array([[[1,2,3,1],
                  [4,5,6,1],
                  [7,8,9,1]],
                 [[1,1,1,1],
                  [1,1,1,1],
                  [1,1,1,1]]])
print(a_mul)
print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)

CPU times: total: 0 ns
Wall time: 0 ns
[[[1 2 3 1]
  [4 5 6 1]
  [7 8 9 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
(2, 3, 4)
3
24
int32


In [27]:
a = np.array([[1,3,4],
              [4,"Hello",6],
              [7,8,9]])
print(a.dtype)

<U11


In [28]:
# <U11 : string less than 11 char

In [29]:
print(a[0][0])
print(type(a[0][0]))

1
<class 'numpy.str_'>


In [30]:
print(a[0][0].dtype)

<U1


In [ ]:
# a = np.array([[1,3,4],
#               [4,"Hello",6],
#               [7,8,9]], dtype=np.int32)
# print(a.dtype)

ValueError: invalid literal for int() with base 10: 'Hello'

In [32]:
a = np.array([[1,3,4],
              [4,"5",6],
              [7,8,9]], dtype=np.int32)
print(a.dtype)

int32


In [33]:
a = np.array([[1,3,4],
              [4,"5",6],
              [7,8,9]])
print(a.dtype)

<U11


In [36]:
a = np.array([[1,3,4],
              [4,"5",6],
              [7,8,9]], dtype=np.float32)
print(a.dtype)
print(a[0][0].dtype)
print(a[0][0])

float32
float32
1.0


In [41]:
d = {'1':'A'}
a = np.array([[1,3,4],
              [4,d,6],
              [7,8,9]])
print(a.dtype)
print(a[1][0])
print(type(a[1][0]))

object
4
<class 'int'>


In [42]:
# more different datatype -> less efficient

In [ ]:
a = np.array([[1,3,4],
              [4,"5",6],
              [7,8,9]], dtype="<U7")
print(a.dtype)
print(a[0][0].dtype)
print(a[0][0])

<U7
<U1
1


In [46]:
a = np.full((2,3,4,2),9)
print(a)

[[[[9 9]
   [9 9]
   [9 9]
   [9 9]]

  [[9 9]
   [9 9]
   [9 9]
   [9 9]]

  [[9 9]
   [9 9]
   [9 9]
   [9 9]]]


 [[[9 9]
   [9 9]
   [9 9]
   [9 9]]

  [[9 9]
   [9 9]
   [9 9]
   [9 9]]

  [[9 9]
   [9 9]
   [9 9]
   [9 9]]]]


In [48]:
a = np.zeros((10,5,2))
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [49]:
a = np.ones((10,5,2))
print(a)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
a = np.empty((10,5,2)) # crates space
print(a)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [54]:
x_values = np.arange(0,1005,5)
print(x_values)

[   0    5   10   15   20   25   30   35   40   45   50   55   60   65
   70   75   80   85   90   95  100  105  110  115  120  125  130  135
  140  145  150  155  160  165  170  175  180  185  190  195  200  205
  210  215  220  225  230  235  240  245  250  255  260  265  270  275
  280  285  290  295  300  305  310  315  320  325  330  335  340  345
  350  355  360  365  370  375  380  385  390  395  400  405  410  415
  420  425  430  435  440  445  450  455  460  465  470  475  480  485
  490  495  500  505  510  515  520  525  530  535  540  545  550  555
  560  565  570  575  580  585  590  595  600  605  610  615  620  625
  630  635  640  645  650  655  660  665  670  675  680  685  690  695
  700  705  710  715  720  725  730  735  740  745  750  755  760  765
  770  775  780  785  790  795  800  805  810  815  820  825  830  835
  840  845  850  855  860  865  870  875  880  885  890  895  900  905
  910  915  920  925  930  935  940  945  950  955  960  965  970  975
  980 

In [55]:
x_values = np.linspace(0,1000,2)
print(x_values)

[   0. 1000.]


In [56]:
x_values = np.linspace(0,1000,4)
print(x_values)

[   0.          333.33333333  666.66666667 1000.        ]


In [57]:
x_values = np.linspace(0,1000,1000)
print(x_values)

[   0.            1.001001      2.002002      3.003003      4.004004
    5.00500501    6.00600601    7.00700701    8.00800801    9.00900901
   10.01001001   11.01101101   12.01201201   13.01301301   14.01401401
   15.01501502   16.01601602   17.01701702   18.01801802   19.01901902
   20.02002002   21.02102102   22.02202202   23.02302302   24.02402402
   25.02502503   26.02602603   27.02702703   28.02802803   29.02902903
   30.03003003   31.03103103   32.03203203   33.03303303   34.03403403
   35.03503504   36.03603604   37.03703704   38.03803804   39.03903904
   40.04004004   41.04104104   42.04204204   43.04304304   44.04404404
   45.04504505   46.04604605   47.04704705   48.04804805   49.04904905
   50.05005005   51.05105105   52.05205205   53.05305305   54.05405405
   55.05505506   56.05605606   57.05705706   58.05805806   59.05905906
   60.06006006   61.06106106   62.06206206   63.06306306   64.06406406
   65.06506507   66.06606607   67.06706707   68.06806807   69.06906907
   70.07

In [58]:
x_values = np.linspace(0,1000,1001)
print(x_values)

[   0.    1.    2. ...  998.  999. 1000.]


In [59]:
print(np.nan)

nan


In [60]:
print(np.inf)

inf


In [61]:
print(np.isnan(np.nan))
print(np.isinf(np.inf))

True
True


In [62]:
print(np.isnan(np.sqrt(-1)))
print(np.isinf(np.array([10])/0))

True
[ True]


C:\Users\hp\AppData\Local\Temp\ipykernel_3008\3338874168.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))
C:\Users\hp\AppData\Local\Temp\ipykernel_3008\3338874168.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.isinf(np.array([10])/0))


In [63]:
print(np.sqrt(-1))
print(np.array([10])/0)

nan
[inf]


C:\Users\hp\AppData\Local\Temp\ipykernel_3008\1603808826.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
C:\Users\hp\AppData\Local\Temp\ipykernel_3008\1603808826.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10])/0)


In [64]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]

In [65]:
a1 = np.array(l1)
a2 = np.array(l2)

In [66]:
print(l1*5)
print(a1*5)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]


In [67]:
print(l1+5)

TypeError: can only concatenate list (not "int") to list

In [69]:
print(a1+5)


[ 6  7  8  9 10]


In [70]:
print(l1+l2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


In [71]:
print(a1+a2)

[ 7  9 11 13  5]


In [72]:
print(l1*l2)

TypeError: can't multiply sequence by non-int of type 'list'

In [73]:
print(a1*a2)

[ 6 14 24 36  0]


In [74]:
print(l1/l2)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [75]:
print(a1/a2)

[0.16666667 0.28571429 0.375      0.44444444        inf]


C:\Users\hp\AppData\Local\Temp\ipykernel_3008\2065770778.py:1: RuntimeWarning: divide by zero encountered in divide
  print(a1/a2)


In [76]:
print(l1-l2)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [77]:
print(a1-a2)

[-5 -5 -5 -5  5]


In [80]:
a1 = np.array([1,2,3])
a2 = np.array([[1],
              [2]])
print(a1+a2)
print(a1*a2)

[[2 3 4]
 [3 4 5]]
[[1 2 3]
 [2 4 6]]


In [83]:
a1 = np.array([1,2,3])
a2 = np.array([[1,1],
              [2,1]])

In [84]:
print(a1+a2)

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [85]:
print(a1*a2)

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [87]:
a = np.array([[1,2,3],
              [4,5,6]])

In [88]:
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [91]:
print("_"*10)
print(np.cos(a))
print("_"*10)
print(np.tan(a))
print("_"*10)
print(np.tanh(a))
print("_"*10)
print(np.log(a))
print("_"*10)
print(np.log10(a))
print("_"*10)

__________
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
__________
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
__________
[[0.76159416 0.96402758 0.99505475]
 [0.9993293  0.9999092  0.99998771]]
__________
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
__________
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]
__________


In [92]:
a = np.array([1,2,3])

In [93]:
np.append(a, [7,8,9])

array([1, 2, 3, 7, 8, 9])

In [94]:
print(a)

[1 2 3]


In [95]:
a = np.append(a, [7,8,9])
print(a)


[1 2 3 7 8 9]


In [96]:
a = np.insert(a,3,[4,5,6])

In [97]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [98]:
a = np.array([[1,2,3],
              [4,5,6]])

In [101]:
print(np.delete(a, 1))
print(np.delete(a, 3))
print(np.delete(a, 4))

[1 3 4 5 6]
[1 2 3 5 6]
[1 2 3 4 6]


In [102]:
print(np.delete(a, 1, 0))
print(np.delete(a, 0, 0))

[[1 2 3]]
[[4 5 6]]


In [103]:
print(np.delete(a, 0, 1))
print(np.delete(a, 1, 1))


[[2 3]
 [5 6]]
[[1 3]
 [4 6]]


In [104]:
# print(np.delete(a, 0-> index, 0 -> 0 for row, 1 for column))

In [105]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])

In [107]:
print(a.shape)
print(a.reshape((5,4)))
print(a.reshape((20,)))
print(a.reshape((20,1)))

(4, 5)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]


In [108]:

print(a.reshape((2,10)))
print(a.reshape((2,2,5)))
print(a.reshape((2,5,2)))
print(a.reshape((5,2,2)))

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


In [109]:
a = a.reshape(5,4)

In [110]:
print(a
      )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [111]:
a.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [112]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [113]:
a.resize((10,2))

In [114]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [115]:
a.resize((4,5))


In [116]:
a


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [117]:
print(a.flatten()) # returns copy
print(a.ravel()) # returns view

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [118]:
var1 = a.flatten()
var1[2] = 100
print(var1)
print(a)

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [119]:
var1 = a.ravel()
var1[2] = 100
print(var1)
print(a)

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[  1   2 100   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [120]:
var = [v for v in a.flat]
print(var)

[1, 2, 100, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [121]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])

In [123]:
print(a.transpose())

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [124]:
print(a.T)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [ ]:
print(a.swapaxes(0,1)) # better for higher dimension arrays

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [128]:
a1 = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
a2 = np.array([[11,12,13,14,15],
              [16,17,18,19,20]])

In [129]:
a = np.concatenate((a1,a2), axis=0)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [130]:
a = np.concatenate((a1,a2), axis=1)
print(a)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [ ]:
a = np.stack((a1,a2)) # adding a new dimension
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [ ]:
a = np.vstack((a1,a2))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
a = np.hstack((a1,a2))
print(a)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [138]:
a = np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12],
              [13,14,15,16,17,18],
              [19,20,21,22,23,24]])

In [139]:
print(np.split(a, 2, axis=0))

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]


In [141]:
print(np.split(a, 4, axis=0))


[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]


In [142]:
print(np.split(a, 2, axis=1))


[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]


In [144]:
print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.sum())
print(np.median(a))

1
24
12.5
6.922186552431729
300
12.5


In [145]:
number = np.random.randint(100)
print(number)

28


In [147]:
numbers = np.random.randint(100, size=(2,3,4))
print(numbers)

[[[84 59 49 78]
  [ 8 49 75 83]
  [44 62 43 93]]

 [[28 47 99 99]
  [48 18 40 59]
  [60  1 70 72]]]


In [148]:
numbers = np.random.randint(2, size=(2,3,4))
print(numbers)

[[[1 0 0 1]
  [1 1 0 1]
  [1 0 0 1]]

 [[0 0 1 1]
  [0 1 0 0]
  [0 0 0 0]]]


In [150]:
numbers = np.random.randint(90,100, size=(2,3,4))
print(numbers)

[[[98 95 96 99]
  [91 91 98 92]
  [90 98 94 90]]

 [[94 90 91 95]
  [96 95 98 98]
  [97 96 98 99]]]


In [151]:
numbers = np.random.binomial(10, p=0.5, size=(5,10))
print(numbers)

[[5 7 7 5 3 4 5 6 7 4]
 [5 4 3 2 5 5 7 8 5 3]
 [7 5 2 5 7 5 6 5 7 6]
 [4 5 5 6 4 4 4 3 7 7]
 [4 6 5 7 4 2 5 6 5 4]]


In [152]:
numbers = np.random.normal(loc=170, scale=15, size=(5,10))
print(numbers)

[[175.82350854 154.99017991 153.85559979 185.10125329 186.47847394
  172.0374158  167.72237827 161.74032259 177.50612998 169.51551683]
 [145.4109128  170.75548824 145.57598421 171.77867863 169.74362787
  191.90903418 159.76667409 174.23203525 174.49077205 173.95815595]
 [176.53258196 172.52545226 148.84713645 178.59455012 202.72521317
  171.04736087 168.79641692 139.82541345 168.82679976 192.20319458]
 [177.5184499  174.4033249  165.21184576 154.99298681 159.73443992
  171.46698194 161.79249262 190.86964158 174.61156063 170.27747758]
 [170.45986018 165.27123477 166.30399918 181.76388139 198.83890444
  149.26628032 157.93437921 178.18790379 165.86322477 176.20310947]]


In [156]:
numbers = np.random.choice([10,20,30,40,50], size=(5,10))
print(numbers)

[[50 50 50 30 20 30 50 10 30 10]
 [40 30 10 30 50 20 40 10 40 20]
 [20 20 20 30 30 20 30 40 50 40]
 [50 20 30 40 50 40 50 50 10 50]
 [40 40 50 20 50 20 40 20 30 10]]


In [157]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [158]:
np.save("myarray.npy", a)

In [159]:
a = np.load("myarray.npy")

In [160]:
np.savetxt("myarray.csv", a, delimiter=",")


In [164]:
a = np.loadtxt("myarray.csv", delimiter=",")
print(a)

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]]
